---
- name: restart opendkim
  systemd:
    name: opendkim
    state: restarted

- name: restart postfix
  systemd:
    name: postfix
    state: restarted

- name: restart postgrey
  systemd:
    name: postgrey
    state: restarted

- name: reload-aliases
  command: /usr/bin/newaliases

- name: postmap-hash
  command: "/usr/sbin/postmap hash:/etc/postfix/{{ item.item }}"
  when: item.changed
  with_items: "{{ postfix_hash_maps.results }}"
