all:
  children:
    cloud:
      hosts:
        cloud.noise: {}
    donate:
      children:
        m5-noisebridge-net: {}
    lists:
      children:
        m6-noisebridge-net: {}
    lists-noisebridge-net:
      children:
        m3-noisebridge-net: {}
    m3-noisebridge-net:
      hosts:
        m3.noisebridge.net: {}
    m4-noisebridge-net:
      hosts:
        m4.noisebridge.net: {}
    m5-noisebridge-net:
      hosts:
        m5.noisebridge.net: {}
    m6-noisebridge-net:
      hosts:
        m6.noisebridge.net: {}
    noisebridge-net:
      children:
        m3-noisebridge-net: {}
    primary-dns-server:
      children:
        m3-noisebridge-net: {}
    secondary-dns-server:
      children:
        m4-noisebridge-net: {}
    smartpi:
      hosts:
        entropi.noise: {}
    space-noisebridge-net:
      hosts:
        pegasus.noisebridge.net: {}

