all:
  children:

# IO Cooperative Servers (m*.noisebridge.net)
# OS: Debian Stretch (Debian 9)
    m3-noisebridge-net:
      hosts:
        # Physical location: Santa Clara, California (IO Cooperative)
        m3.noisebridge.net: {}
    m4-noisebridge-net:
      hosts:
        # Physical location: Minneapolis, Minnesota (IO Cooperative)
        m4.noisebridge.net: {}
    m5-noisebridge-net:
      hosts:
        # Physical location: Santa Clara, California (IO Cooperative)
        m5.noisebridge.net: {}
    m6-noisebridge-net:
      hosts:
        # Physical location: Santa Clara, California (IO Cooperative)
        m6.noisebridge.net: {}

# Physical Servers located in Noisebridge (2169 Mission St., 3rd Floor)
    smartpi:
      hosts:
        entropi.noise: {}
    space-noisebridge-net:
      hosts:
        # OS: Debian Stretch (Debian 9)
        pegasus.noisebridge.net: {}
    cloud:
      hosts:
        cloud.noise: {}

# Aliases (production)
    noisebridge-net:
      children:
        m3-noisebridge-net: {}
    lists-noisebridge-net:
      children:
        m3-noisebridge-net: {}
    primary-dns-server:
      children:
        m3-noisebridge-net: {}
    secondary-dns-server:
      children:
        m4-noisebridge-net: {}

# Aliases (development)
    donate:
      children:
        m5-noisebridge-net: {}
    lists:
      children:
        m6-noisebridge-net: {}
