---

- name: node defaults
  hosts: all
  become: yes
  become_method: sudo
  tags: [common]
  roles:
    - utils
    - security
    - jnv.unattended-upgrades

- name: noisebridge-net
  hosts: noisebridge-net
  become: yes
  become_method: sudo
  tags: [noisebridge-net]
  roles:
    - antoiner77.caddy
    - mediawiki
    - { role: website, tags: [ 'website' ] }
    - cloudalchemy.node-exporter
    - { role: cloudalchemy.prometheus, tags: [ 'prometheus' ] }
    - { role: mydumper, tags: [ 'mydumper' ] }
  vars:
    mediawiki:
      database: noisebridge_mediawiki
      database_username: wiki
      domain: noisebridge.net

- name: List server
  hosts: lists-noisebridge-net
  become: yes
  become_method: sudo
  tags: [lists-noisebridge-net]
  roles:
    - postfix
    - mailman

- name: Primary DNS Server
  hosts: dns
  become: yes
  become_method: sudo
  tags: [dns]
  roles:
    - coredns

- name: Space
  hosts: space-noisebridge-net
  become: yes
  become_method: sudo
  tags: [space-noisebridge-net]
  roles:
    - cloudalchemy.node-exporter
    - { role: cloudalchemy.snmp-exporter, tags: [ 'snmp' ] }
    - { role: cloudalchemy.prometheus, tags: [ 'prometheus' ] }
    - cloudalchemy.grafana
    - powerpanel
    
- name: Mailman-3 List server
  hosts: lists
  become: yes
  become_method: sudo
  tags: [lists]
  roles:
    - postfix
    - mailman3

- name: Nextcloud on debian box in space
  hosts: cloud
  become: yes
  become_method: sudo
  tags: [cloud]
  roles:
    - nextcloud-docker

- name: Parts service
  hosts: parts-noisebridge-net
  become: yes
  become_method: sudo
  tags: [parts-noisebridge-net]
  roles:
    - antoiner77.caddy
    - { role: stuff-org, tags: [ 'stuff-org' ] }

- name: Earl RFID Access
  hosts: earl
  become: yes
  become_method: sudo
  tags: [earl]
  roles:
    - earl
