---

- name: node defaults
  hosts: all
  become: yes
  become_method: sudo
  tags: [common]
  roles:
    - utils
    - security

- name: noisebridge-net
  hosts: noisebridge-net
  become: yes
  become_method: sudo
  tags: [noisebridge-net]
  roles:
    - mediawiki
    - spiped
  vars:
    web_domains:
      m3.noisebridge.net:
        - m3.noisebridge.net
    mediawiki:
      database: noisebridge_mediawiki
      database_username: wiki
      domain: m3.noisebridge.net
      release: 1.27 # needed for URL construction for downloading
      release_sha256sum: 08a676c392625cf3c5730a6c1b9390ab1e11dcc17cfd0ff97a2ae3917ef5a36a
      version: 1.27.1
    certbot_certs:
      m3.noisebridge.net:
        - m3.noisebridge.net

- name: DNS Server
  hosts: primary-dns-server
  become: yes
  become_method: sudo
  tags: [primary-dns-server]
  roles:
    - coredns

- name: Mail Server
  hosts: mail-server
  become: yes
  become_method: sudo
  tags: [noisebridge-net]
  roles:
    - debops.postfix
    - debops.mailman
