---

- name: Version precheck
  hosts: all
  gather_facts: False
  tags:
  - always
  pre_tasks:
  - name: Verify Ansible meets version requirements.
    assert:
      that: "ansible_version.full is version_compare('2.8', '>=')"
      msg: >
        "You must update Ansible to at least 2.8."

# Workaround for https://github.com/ansible/ansible/issues/57529
- hosts: all

- name: node defaults
  hosts: all
  become: yes
  become_method: sudo
  tags: [common]
  roles:
    - utils
    - security
    - jnv.unattended-upgrades

- name: noisebridge-net
  hosts: noisebridge-net
  become: yes
  become_method: sudo
  tags: [noisebridge-net]
  roles:
    - { role: mediawiki, tags: [ 'mediawiki' ] }
    - { role: website, tags: [ 'website' ] }
    - { role: safespace, tags: [ safespace' ] }
    - cloudalchemy.node-exporter
    - { role: cloudalchemy.blackbox-exporter, tags: [ 'blackbox' ] }
    - { role: cloudalchemy.prometheus, tags: [ 'prometheus' ] }
    - { role: mydumper, tags: [ 'mydumper' ] }
    - { role: caddy, tags: [ 'caddy' ] }

- name: donate-noisebridge-net
  hosts: donate-noisebridge-net
  become: yes
  become_method: sudo
  tags: [donate]
  roles:
    - donate
    - percona
    - geerlingguy.mysql
    - caddy
    - pydonate

- name: List server
  hosts: lists-noisebridge-net
  become: yes
  become_method: sudo
  tags: [lists-noisebridge-net]
  roles:
    - postfix
    - mailman

- name: Primary DNS Server
  hosts: dns
  become: yes
  become_method: sudo
  tags: [dns]
  roles:
    - coredns

- name: Space
  hosts: space-noisebridge-net
  become: yes
  become_method: sudo
  tags: [space-noisebridge-net]
  roles:
    - cloudalchemy.node-exporter
    - { role: cloudalchemy.snmp-exporter, tags: [ 'snmp' ] }
    - { role: unifi-poller, tags: [ 'unifi-poller' ] }
    - { role: cloudalchemy.prometheus, tags: [ 'prometheus' ] }
    - cloudalchemy.grafana
    - powerpanel

- name: Mailman-3 List server
  hosts: lists
  become: yes
  become_method: sudo
  tags: [lists]
  roles:
    - postfix
    - mailman3

- name: Nextcloud on debian box in space
  hosts: cloud
  become: yes
  become_method: sudo
  tags: [cloud]
  roles:
    - nextcloud-docker

- name: Misc web services
  hosts: m4-noisebridge-net
  become: yes
  become_method: sudo
  tags: [m4-noisebridge-net]
  roles:
    - { role: caddy, tags: [ 'caddy' ] }
    - { role: library-org, tags: [ 'library-org' ] }
    - { role: stuff-org, tags: [ 'stuff-org' ] }

- name: Earl RFID Access
  hosts: earl
  become: yes
  become_method: sudo
  tags: [earl]
  roles:
    - earl

- name: Power monitoring
  hosts: smartpi
  tags: [smartpi]
  roles:
    - smartpi
