---
- name: install application dependencies
  with_items:
    - postgresql-9.6  # postgresql database
    - libpq-dev       # postgresql client headers for ruby gem
    - python-psycopg2 # ansible postgresql utilities dependencies
    - rbenv           # Ruby version manager
  apt:
    package: "{{ item }}"

- name: ensure group for local user exists
  group:
    name: "{{ donate_user }}"
    state: present

- name: ensure local user exists
  user:
    name: "{{ donate_user }}"
    groups: "{{ donate_user }}"
    home: "/srv/{{ donate_user }}"
    createhome: yes
    shell: /bin/bash

- name: Get the current ruby version
  set_fact:
    ruby_version: "{{ lookup('url', 'https://raw.githubusercontent.com/noisebridge/donate.noisebridge.net/master/.ruby-version') }}"

- name: install ruby version
  become_user: "{{ donate_user }}"
  become_method: sudo
  shell: "rbenv install {{ ruby_version }}"
  args:
    chdir: "/srv/{{ donate_user }}"
    creates: "/srv/{{ donate_user }}/.rbenv/versions/{{ ruby_version }}/bin/ruby"

- name: configure rbenv shell script for user
  blockinfile:
    owner: "{{ donate_user }}"
    group: "{{ donate_user }}"
    create: yes
    dest: "/srv/{{ donate_user }}/.bashrc"
    block: |
      eval "$(rbenv init -)"

- name: create the donate database
  become_user: postgres
  become_method: sudo
  postgresql_db:
    db: "{{ noisebridge_donate.database_name }}"
    encoding: UTF-8
    state: present

- name: create the donate user
  become_user: postgres
  become_method: sudo
  postgresql_user:
    name: "{{ noisebridge_donate.database_username }}"
    state: present
    password: "{{ noisebridge_donate.database_password }}"

- name: grant privs for database
  become_user: postgres
  become_method: sudo
  postgresql_privs:
    db: "{{ noisebridge_donate.database_name }}"
    privs: ALL
    role: "{{ noisebridge_donate.database_username }}"
    type: database

- name: clone the application source
  become: "{{ donate_user }}"
  become_method: sudo
  git:
    repo: https://github.com/noisebridge/donate.noisebridge.net.git
    dest: "/srv/{{ donate_user }}/noisebridge-donate"


#- name: install Ruby dependencies
#  become: "{{ donate_user }}"
#  become_method: sudo
#  shell: "/srv/{{ donate_user }}/.rbenv/bin/rbenv exec bundle install" 
#  args:
#    chdir: "/srv/{{ donate_user }}/noisebridge-donate-{{ donate_head.stdout }}"
