---
- name: install application dependencies
  with_items:
    - postgresql-9.6  # postgresql database
    - libpq-dev       # postgresql client headers for ruby gem
    - python-psycopg2 # ansible postgresql utilities dependencies
  apt:
    package: "{{ item }}"

- name: create the donate database
  become_user: postgres
  become_method: sudo
  postgresql_db:
    db: "{{ noisebridge_donate.database_name }}"
    encoding: UTF-8
    state: present

- name: create the donate user
  become_user: postgres
  become_method: sudo
  postgresql_user:
    name: "{{ noisebridge_donate.database_username }}"
    state: present
    password: "{{ noisebridge_donate.database_password }}"

- name: grant privs for database
  become_user: postgres
  become_method: sudo
  postgresql_privs:
    db: "{{ noisebridge_donate.database_name }}"
    privs: ALL
    role: "{{ noisebridge_donate.database_username }}"
    type: database

- name: clone the application source
  become: "{{ user }}"
  become_method: sudo
  git:
    repo: https://github.com/noisebridge/donate.noisebridge.net.git
    dest: "/srv/{{ user }}/noisebridge-donate"

- name: determine the HEAD of the repository
  become: "{{ user }}"
  become_method: sudo
  shell: git rev-parse HEAD
  args:
    chdir: "/srv/{{ user }}/noisebridge-donate"
  register: donate_head

- name: determine if source is checked out
  stat:
    path: "/srv/{{ user }}/noisebridge-donate-{{ donate_head.stdout }}"
  register: donate_checkout

- name: ensure checkout of latest master exists
  file:
    path: "/srv/{{ user }}/noisebridge-donate-{{ donate_head.stdout }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"

- name: extract the git archive
  become: "{{ user }}"
  become_method: sudo
  shell: "git archive master | tar -x -C /srv/{{ user}}/noisebridge-donate-{{ donate_head.stdout }}"
  args:
    chdir: "/srv/{{ user }}/noisebridge-donate"

- name: install Ruby dependencies
  become: "{{ user }}"
  become_method: sudo
  shell: "/srv/{{ user }}/.rbenv/bin/rbenv exec bundle install" 
  args:
    chdir: "/srv/{{ user }}/noisebridge-donate-{{ donate_head.stdout }}"
