---
- name: create web root
  file:
    dest: /var/www/donate.noisebridge.net
    state: directory
    owner: root
    group: root
    mode: 0755

- name: copy static page
  template:
    src: index.html
    dest: /var/www/donate.noisebridge.net/index.html
    owner: root
    group: root
    mode: 0644
