---

- import_tasks: users.yml

#- name: install logwatch & sendmail
#  items:
#    - logwatch
#    - sendmail
#  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=3600
#  tags:
#    - security
#    - logwatch

#- name: configure daily logwatch email
#  copy:
#    src: 00logwatch
#    dest: /etc/cron.daily/00logwatch
#  tags:
#    - security

- name: Disallow password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: restart sshd
