---
- name: Add user
  user:
    name: "{{ item }}"
    comment: "{{ users[item].fullname }}"
    shell: "{{ users[item].shell | default('/bin/bash') }}"
  with_flattened:
  - "{{ noisebridge_admins }}"
  - "{{ noisebridge_users }}"

- name: Grant sudo
  user:
    name: "{{ item }}"
    groups:
    - "sudo"
    append: yes
  with_flattened:
  - "{{ noisebridge_admins | d([]) }}"

- name: github SSH key
  authorized_key:
    user: "{{ item }}"
    key: "https://github.com/{{ users[item].github_username }}.keys"
  with_flattened:
  - "{{ noisebridge_admins | d([]) }}"
  - "{{ noisebridge_users | d([]) }}"
  when: users[item].github_username is defined

- name: static SSH key
  authorized_key:
    user: "{{ item }}"
    key: "{{ users[item].ssh_key }}"
  with_flattened:
  - "{{ noisebridge_admins | d([]) }}"
  - "{{ noisebridge_users | d([]) }}"
  when: users[item].ssh_key is defined
