---
- name: install key
  apt_key:
    url: https://golift.io/gpgkey

- name: setup repo
  apt_repository:
    repo: "deb https://dl.bintray.com/golift/{{ ansible_distribution | lower }} {{ ansible_lsb.codename }} {{ unifi_poller_apt_release }}"
    update_cache: true

- name: install
  apt:
    name: "unifi-poller={{ unifi_poller_version }}"

- name: configure
  template:
    src: up.conf.j2
    dest: /etc/unifi-poller/up.conf
    owner: root
    group: root
    mode: 0644
  notify:
  - restart unifi-poller
