---
blackbox_exporter_web_listen_address: "127.0.0.1:9115"
blackbox_exporter_configuration_modules:
  http_2xx_v4:
    prober: http
    http:
      preferred_ip_protocol: "ip4"
      ip_protocol_fallback: false
  http_2xx_v6:
    prober: http
    http:
      preferred_ip_protocol: "ip6"
      ip_protocol_fallback: false
  smtp_starttls_v4:
    prober: tcp
    tcp:
      preferred_ip_protocol: "ip4"
      ip_protocol_fallback: false
      query_response:
        - expect: "^220 ([^ ]+) ESMTP (.+)$"
        - send: "EHLO prober"
        - expect: "^250-STARTTLS"
        - send: "STARTTLS"
        - expect: "^220"
        - starttls: true
        - send: "EHLO prober"
        - expect: "^250-"
        - send: "QUIT"
  smtp_starttls_v6:
    prober: tcp
    tcp:
      preferred_ip_protocol: "ip6"
      ip_protocol_fallback: false
      query_response:
        - expect: "^220 ([^ ]+) ESMTP (.+)$"
        - send: "EHLO prober"
        - expect: "^250-STARTTLS"
        - send: "STARTTLS"
        - expect: "^220"
        - starttls: true
        - send: "EHLO prober"
        - expect: "^250-"
        - send: "QUIT"
