---
caddy_packages:
- github.com/aksdb/caddy-cgi/v2
caddy_config: "{{ lookup('template', 'templates/caddy/m3/Caddyfile.j2') }}"

noisebridge_mailman_cgi_scripts:
- admin
- admindb
- confirm
- create
- edithtml
- listinfo
- options
- private
- rmlist
- roster
- subscribe
