---
- name: Install packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - ack-grep
      - apt-transport-https
      - bash-completion
      - bind9-host
      - ca-certificates
      - curl
      - debconf
      - debconf-utils
      - dnsutils
      - file
      - git
      - htop
      - iftop
      - inotify-tools
      - iotop
      - less
      - libcap2-bin
      - lsof
      - mosh
      - mtr-tiny
      - screen
      - strace
      - sudo
      - tcpdump
      - vim

- name: Setup sudoers
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%sudo"
    line: "%sudo	ALL=(ALL:ALL) NOPASSWD: ALL" # noqa 203
    state: present
    mode: 0440
