---
- name: Install apt dependencies
  apt:
    name: "{{ deps }}"
  vars:
    deps:
      - python3
      - python3-setuptools
      - virtualenv
      - git
      - build-essential
      - libpython3-dev
      - libssl-dev

- name: Create group for pydonate
  group:
    name: "{{ pydonate_user }}"
    state: present
    system: yes

- name: Create user for pydonate
  user:
    name: "{{ pydonate_user }}"
    group: "{{ pydonate_user }}"
    home: "/srv/{{ pydonate_user }}"
    createhome: false
    shell: /sbin/nologin
    system: yes


- name: Create dirs
  file:
    path: "{{ item }}"
    owner: "{{ pydonate_user }}"
    group: "{{ pydonate_user }}"
    state: directory
    mode: 0755
  with_items:
  - "/srv/{{ pydonate_user }}"

- name: Checkout repository
  become_user: "{{ pydonate_user }}"
  git:
    repo: https://github.com/noisebridge/python-nb-donate.git
    dest: "/srv/{{ pydonate_user }}/code"
    update: yes
  notify:
  - restart pydonate

- name: Setup venv
  become_user: "{{ pydonate_user }}"
  pip:
    requirements: "/srv/{{ pydonate_user }}/code/requirements.txt"
    virtualenv: "/srv/{{ pydonate_user }}/code/venv"
    virtualenv_python: python3.5

- name: "-e ."
  become_user: "{{ pydonate_user }}"
  pip:
    name: "/srv/{{ pydonate_user }}/code"
    virtualenv: "/srv/{{ pydonate_user }}/code/venv"
    virtualenv_python: python3.5

- name: Template out systemd file
  template:
    src: pydonate.service
    dest: /etc/systemd/system/pydonate.service
    owner: root
    group: root
    mode: '0644'
  notify:
  - reload pydonate service file

- name: Template out .env file
  template:
    src: dot_env
    dest: "/srv/{{ pydonate_user }}/code/.env"
    owner: root
    group: "{{ pydonate_user }}"
    mode: '0640'
  notify:
  - restart pydonate
