---
- name: Install apt dependencies
  apt:
    name: "{{ deps }}"
  vars:
    deps:
      - python3
      - python3-setuptools
      - virtualenv
      - git
      - build-essential
      - libpython3-dev
      - libssl-dev

- name: Create group for pydonate
  group:
    name: "{{ pydonate_user }}"
    state: present
    system: yes

- name: Create user for pydonate
  user:
    name: "{{ pydonate_user }}"
    group: "{{ pydonate_user }}"
    home: "/srv/{{ pydonate_user }}"
    createhome: false
    shell: /sbin/nologin
    system: yes

- name: Create dirs
  file:
    path: "{{ item }}"
    owner: "{{ pydonate_user }}"
    group: "{{ pydonate_user }}"
    state: directory
    mode: 0755
  with_items:
  - "/srv/{{ pydonate_user }}"
  - "{{ pydonate_base }}"

- name: Checkout repository
  become: true
  become_user: "{{ pydonate_user }}"
  git:
    repo: https://github.com/noisebridge/python-nb-donate.git
    dest: "{{ pydonate_base }}"
    version: "{{ pydonate_version }}"
  notify:
  - restart pydonate

- name: Setup venv
  become: true
  become_user: "{{ pydonate_user }}"
  pip:
    requirements: "{{ pydonate_base }}/requirements.txt"
    virtualenv: "{{ pydonate_base }}/venv"
    virtualenv_python: python3.7

- name: "-e ."
  become: true
  become_user: "{{ pydonate_user }}"
  pip:
    editable: true
    name: "{{ pydonate_base }}"
    virtualenv: "{{ pydonate_base }}/venv"
    virtualenv_python: python3.7

- name: Template out systemd file
  template:
    src: pydonate.service
    dest: /etc/systemd/system/pydonate.service
    owner: root
    group: root
    mode: '0644'
  notify:
  - reload pydonate service file

- name: Template out .env file
  template:
    src: dot_env
    dest: "{{ pydonate_base }}/.env"
    owner: root
    group: "{{ pydonate_user }}"
    mode: '0640'
  notify:
  - restart pydonate

  # - include: initialize_app.yml
