---
grafana_port: 3001
grafana_address: 127.0.0.1

grafana_security:
  admin_user: admin
  admin_password: "{{ grafana_admin_password }}"

grafana_auth:
  anonymous:
    org_name: Noisebridge
    org_role: Viewer
