---
node_exporter_web_listen_address: ":9100"
prometheus_web_listen_address: ":9090"
prometheus_storage_retention: "90d"
prometheus_global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 30s
prometheus_scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
        - "pegasus.noisebridge.net:9090"
  - job_name: "node"
    static_configs:
      - targets:
        - "pegasus.noisebridge.net:9100"
  - job_name: "smartpi"
    scrape_interval: 1s
    static_configs:
      - targets:
        - "entropi.noise:9246"
  - job_name: "earl"
    static_configs:
      - targets:
        - "earl.noise:1212"

prometheus_targets: {}
