---
caddy_features: http.prometheus
caddy_config: |
  library.noisebridge.net {
    prometheus
    gzip
    log "{{ caddy_log_dir }}/library.noisebridge.net.log" {
      rotate_size 50
      rotate_age 7
      rotate_keep 520
      rotate_compress
      ipmask 255.255.0.0 ffff:ffff:ffff:ff00::
    }
    header / {
      Strict-Transport-Security "max-age=31536000;includeSubdomains"
      X-XSS-Protection "1; mode=block"
      X-Content-Type-Options "nosniff"
    }
    proxy / localhost:5000 {
      transparent
    }
  }
  parts.noisebridge.net {
    prometheus
    gzip
    log "{{ caddy_log_dir }}/parts.noisebridge.net.log" {
      rotate_size 50
      rotate_age 7
      rotate_keep 520
      rotate_compress
      ipmask 255.255.0.0 ffff:ffff:ffff:ff00::
    }
    header / {
      Strict-Transport-Security "max-age=31536000;includeSubdomains"
      X-XSS-Protection "1; mode=block"
      X-Content-Type-Options "nosniff"
    }
    proxy / localhost:3000 {
      transparent
    }
  }
