---
- name: install php
  apt:
    update_cache: yes
    cache_valid_time: 3600
    package:
    - imagemagick
    - php7.0
    - php7.0-mysql
    - php7.0-imagick
    - php7.0-fpm
    - php7.0-mbstring
    - php7.0-xml
    - composer
  tags:
  - apt
  - php

- name: Configure PHP FPM
  copy:
    src: php/www.conf
    dest: /etc/php/7.0/fpm/pool.d/www.conf
  tags:
    - php
  notify:
    - restart php7.0-fpm
